#config_version=6

##! mode: chair_lit
mode:
  priority: 300
  start_events: center_ramp_active, mode_mansion_awards_started
  stop_events: balldevice_electric_chair_ball_enter, balldevice_swamp_kickout_ball_enter
event_player:
  mode_chair_lit_stopping: unlight_chair
  mode_chair_lit_started: light_chair, cancel_chair_timer
  mode_chair_lit_3s_started: cancel_chair_timer
counters:
  initialize_mansion:
    count_events: mode_chair_lit_started
    events_when_complete: initialize_mansion
    count_complete_value: 1
    persist_state: true

# queue_relay_player:
#   balldevice_bd_scoop_ball_eject_attempt:
#     post: start_mode_success_show
#     wait_for: mode_success_show_ended
# show_player:
#   start_mode_success_show:
#     success_show:
#       loops: 0
#       events_when_completed: mode_success_show_ended
# shows:
#   success_show:
#     - duration: 10