#config_version=6

##! mode: pop_bumpers
mode:
  start_events: ball_starting
  stop_events: ball_will_end
  priority: 200

# Use a counter to track pop bumper hits
counters:
  pop_bumper_counter:
    count_events: shot_pop1_hit, shot_pop2_hit, shot_pop3_hit, shot_pop4_hit, shot_pop5_hit
    count_complete_value: 20
    events_when_complete: pop_bumpers_20_hits_reached
    enable_events: mode_pop_bumpers_started
    reset_events: ball_starting

# Define shot profiles for pop bumpers with LED control
shot_profiles:
  pop_bumper_profile:
    states:
      - name: unlit
        show: off
      - name: lit
        show: "on"
      - name: complete
        show: flash
        loops: 5

  pop_bumper_scoop_profile:
    advance_on_hit: false
    states:
      - name: unlit
        show: off
      - name: lit
        show: show_blink

# Pop bumper shots are defined in base mode, we just need to add show_tokens
# We'll use show_player to control the LEDs directly since we can't overload shots

event_player:
  # When the mode starts, reset the pop bumper counter
  mode_pop_bumpers_started: reset_pop_bumpers
  # When 20 hits are reached, complete the mode and trigger reward collection
  pop_bumpers_20_hits_reached:
    - pop_bumpers_complete
    - enable_pop_bumpers_reward


variable_player:
  # Score for each pop bumper hit (these events are generated by the base mode shots)
  shot_pop1_hit:
    score: 1000
  shot_pop2_hit:
    score: 1000
  shot_pop3_hit:
    score: 1000
  shot_pop4_hit:
    score: 1000
  shot_pop5_hit:
    score: 1000

  # When 20 hits are reached, complete the mode and trigger reward collection
  pop_bumpers_20_hits_reached:
    pop_bumpers_completed: 1
  
  # Bonus score when completing the mode
  pop_bumpers_complete:
    score: 20000

show_player:
  # Light up pop bumpers when mode starts
  mode_pop_bumpers_started:
    led_pop1:
      show: "on"
    led_pop2:
      show: "on"
    led_pop3:
      show: "on"
    led_pop4:
      show: "on"
    led_pop5:
      show: "on"
  
  # Flash all pop bumpers when mode is completed
  pop_bumpers_complete:
    led_pop1:
      show: flash
      loops: 5
    led_pop2:
      show: flash
      loops: 5
    led_pop3:
      show: flash
      loops: 5
    led_pop4:
      show: flash
      loops: 5
    led_pop5:
      show: flash
      loops: 5

sound_player: 
  # Sound for each pop bumper hit
  shot_pop1_hit:
    blue_target:
      action: play
  shot_pop2_hit:
    blue_target:
      action: play
  shot_pop3_hit:
    blue_target:
      action: play
  shot_pop4_hit:
    blue_target:
      action: play
  shot_pop5_hit:
    blue_target:
      action: play
  
  # Sound when 20 hits are reached
  pop_bumpers_20_hits_reached:
    grave_complete:
      action: play
  
  # Special sound when mode is completed
  pop_bumpers_complete:
    grave_complete:
      action: play
