#config_version=6

##! mode: pop_bumpers
mode:
  start_events: ball_starting
  stop_events: ball_will_end
  priority: 200

counters:
  pop_bumper_counter:
    count_events: s_pop1_active, s_pop2_active, s_pop3_active, s_pop4_active, s_pop5_active
    count_complete_value: 20
    events_when_complete: pop_bumpers_20_hits_reached, pop_mode_complete
    enable_events: mode_pop_bumpers_started
    reset_events: ball_starting

event_player:
  # When the mode starts, reset the pop bumper counter
  # mode_pop_bumpers_started: reset_pop_bumpers
  # When 20 hits are reached, complete the mode and trigger reward collection
  # pop_bumpers_20_hits_reached:
  #   - pop_bumpers_complete
  #   - enable_pop_bumpers_reward

show_player:
  pop_bumpers_20_hits_reached:
    led_mansion:
      show: led_mansion_pop
      loops: 0


sound_player:
  pop_bumpers_20_hits_reached:
    coin_complete: play

variable_player:
  # switch hits
  pop_bumpers_20_hits_reached:
    score: 50000