#config_version=6

show_player:
  mode_attract_started:
    # mansion_attract_show_1:
    #     speed: 2
    #     loops: 2
    # mansion_attract_show_2:
    #     speed: 2
    #     loops: -1
    mansion_attract_show_1:
        speed: 4

    lane_left_attract_show_2:
        speed: 1

    lane_right_attract_show_1:
        speed: 1
    
    letter_attract_show:
        speed: 2

    thunder_show_1:
        speed: 2

    swamp_show_1:
        speed: 2