#config_version=6

##! mode: base
mode:
  start_events: ball_starting
  priority: 250

counters:
  right_ramp_counter:
    starting_count: 0
    start_enabled: true
    persist_state: true
    reset_on_complete: false
    count_events: right_ramp_hit
  top_loop_counter:
    starting_count: 0
    count_events: top_loop_hit
    start_enabled: true
    persist_state: true
    reset_on_complete: false

sequence_shots:
  right_ramp:
    switch_sequence: s_right_ramp_entry, s_right_ramp_top
    sequence_timeout: 3s
  left_ramp:
    switch_sequence: s_left_ramp_entry, s_left_ramp_top
    sequence_timeout: 3s
  top_loop:
    switch_sequence: s_top_loop_entry, s_upper_right_loop
    sequence_timeout: 3s

shots:
  shot_right_inlane:
    switch: s_right_inlane
    show_tokens:
      led: led_right_inlane
  shot_right_outlane:
    switch: s_right_outlane
    show_tokens:
      led: led_right_outlane
  shot_left_inlane_1:
    switch: s_left_inlane_1
    show_tokens:
      led: led_left_inlane_1
  shot_left_inlane_2:
    switch: s_left_inlane_2
    show_tokens:
      led: led_left_inlane_2
  shot_left_outlane:
    switch: s_left_outlane
    show_tokens:
      led: led_left_outlane

variable_player:
  # switch hits
  s_pop1_active:
    score: 200
  s_pop2_active:
    score: 200
  s_pop3_active:
    score: 200
  s_pop4_active:
    score: 200
  s_pop5_active:
    score: 200

  s_left_slingshot_active:
    score: 50
  s_right_slingshot_active:
    score: 50

  s_it_hole_active:
    score: 200

  #shot hits
  shot_right_ramp_hit:
    score: 100
  shot_right_scoop_hit:
    score: 100

show_player:
  s_pop1_active:
    led_gy:
      show: led_gy_blink
      loops: 0
  s_pop2_active:
    led_gy:
      show: led_gy_blink
      loops: 0
  s_pop3_active:
    led_gy:
      show: led_gy_blink
      loops: 0
  s_pop4_active:
    led_gy:
      show: led_gy_blink
      loops: 0
  s_pop5_active:
    led_gy:
      show: led_gy_blink
      loops: 0
  s_left_slingshot_active:
    led_gy:
      show: led_sling_blink
      loops: 0
  s_right_slingshot_active:
    led_gy:
      show: led_sling_blink
      loops: 0

slide_player:
  mode_base_started:
    widgets:
      - type: text
        text: (score)
        number_grouping: true
        min_digits: 2
        font_size: 200
        font_name: MetalMania-Regular.ttf
      - type: text
        text: PLAYER (number)
        y: 10
        x: 10
        font_size: 50
        font_name: MetalMania-Regular.ttf
        anchor_x: left
        anchor_y: bottom
      - type: text
        text: BALL (ball)
        y: 10
        x: right-10
        anchor_x: right
        anchor_y: bottom
        font_size: 50
        font_name: MetalMania-Regular.ttf
      - type: image
        image: onepiece
        x: center
        y: middle

light_player:
  mode_base_started:
    led_gi_left_ball_guide_1: white
    led_gi_left_ball_guide_2: white
    led_gi_left_ball_guide_3: white
    led_gi_right_ball_guide_1: white
    led_gi_right_ball_guide_2: white
    led_gi_right_slingshot: white
    led_gi_left_slingshot: white
    led_gi_pops: white
    led_gi_grtargets: white
    led_gi_smallflip: white

  mode_base_ended:
    led_gi_left_ball_guide_1: off
    led_gi_left_ball_guide_2: off
    led_gi_left_ball_guide_3: off
    led_gi_right_ball_guide_1: off
    led_gi_right_ball_guide_2: off
    led_gi_right_slingshot: off
    led_gi_left_slingshot: off
    led_gi_pops: off
    led_gi_grtargets: off
    led_gi_smallflip: off

sound_player:
  #music
  mode_base_started:
    music_startuplong:
      action: stop
      fade_out: 0s
    music_prelaunch:
      action: play

  playfield_active:
    dragon_roost:
      action: play
    music_prelaunch:
      action: stop
      fade_out: 1s
  #sfx on hit
  s_left_slingshot_active:
    slingshot:
      action: play

  s_right_slingshot_active:
    slingshot:
      action: play

  s_pop1_active:
    coin:
      action: play
  s_pop2_active:
    coin:
      action: play
  s_pop3_active:
    coin:
      action: play
  s_pop4_active:
    coin:
      action: play
  s_pop5_active:
    coin:
      action: play