#config_version=6

##! mode: ghost_ship
mode:
  start_events: ball_starting
  stop_events: ship_ghost_ship_mode_complete
  priority: 200

counters:
  ghost_ship_counter:
    count_events: shot_left_orbit_hit
    count_complete_value: 2
    events_when_complete: ghost_ship_mode_complete
    enable_events: mode_ghost_ship_started
    reset_events: ball_starting

event_player:
  ghost_ship_mode_complete:
    - ghost_ship_complete

variable_player:
  shot_left_orbit_hit:
    score: 1000
  ghost_ship_complete:
    score: 3000

show_player:
  shot_left_orbit_hit:
    led_advance:
      show: show_blink
      loops: 0

  ghost_ship_mode_complete:
    led_advance:
      show: "on"
      loops: 0

sound_player:

  shot_left_orbit_hit:
    sword_slice:
      action: play
