#config_version=6

##! mode: grave_targets
mode:
  start_events: ball_starting
  stop_events: ball_will_end
  priority: 200

sequences:
  grave_targets_sequence:
    events:
      - shot_target_g_lit_hit
      - shot_target_r_lit_hit
      - shot_target_a_lit_hit
      - right_ramp_hit
      - shot_right_scoop_lit_hit
    restart_events: reset_targets
    events_when_complete: grave_targets_sequence_complete

shot_groups:
  grave_targets_group:
    shots: shot_target_g, shot_target_r, shot_target_a, shot_right_ramp

event_player:
  # When the mode starts, reset the drop sequence
  mode_grave_targets_started: reset_targets
  # When the sequence resets, advance the first target
  reset_targets: advance_target_g
  # When right scoop is hit, make it solid and trigger mansion light blinking
  shot_right_scoop_lit_hit:
    - grave_targets_complete

shots:
  shot_target_g:
    switches: s_target_g
    profile: target_profile_g
    advance_events: advance_target_g, shot_target_g_lit_hit
    reset_events: reset_targets
    show_tokens:
      led: led_letter_g
  shot_target_r:
    switches: s_target_r
    profile: target_profile_r
    advance_events: shot_target_g_lit_hit, shot_target_r_lit_hit
    reset_events: reset_targets
    show_tokens:
      led: led_letter_r
  shot_target_a:
    switches: s_target_a
    profile: target_profile_a
    advance_events: shot_target_r_lit_hit, shot_target_a_lit_hit
    reset_events: reset_targets
    show_tokens:
      led: led_letter_a
  shot_right_ramp:
    hit_events: right_ramp_hit
    profile: target_profile_ramp
    advance_events: shot_target_a_lit_hit, right_ramp_hit
    reset_events: reset_targets
    show_tokens:
      led: led_ramp_1
  shot_right_scoop:
    switches: s_right_scoop
    profile: scoop_profile
    advance_events: right_ramp_hit, advance_scoop_to_solid
    reset_events: reset_targets
    show_tokens:
      led: led_letter_e

shot_profiles:
  target_profile_g:
    advance_on_hit: false
    states:
      - name: off
        show: off
      - name: lit
        show: show_blink
      - name: down
        show: "on"
  target_profile_r:
    advance_on_hit: false
    states:
      - name: off
        show: off
      - name: lit
        show: show_blink
      - name: down
        show: "on"
  target_profile_a:
    advance_on_hit: false
    states:
      - name: off
        show: off
      - name: lit
        show: show_blink
      - name: down
        show: "on"
  target_profile_ramp:
    advance_on_hit: false
    states:
      - name: off
        show: off
      - name: lit
        show: show_blink
      - name: down
        show: "on"

  scoop_profile:
    advance_on_hit: false
    states:
      - name: unlit
        show: off
      - name: lit
        show: show_blink
      - name: solid
        show: "on"


variable_player:
  shot_target_g_hit:
    score: 1000
  shot_target_r_hit:
    score: 1000
  shot_target_a_hit:
    score: 1000
  right_ramp_hit:
    score: 1000

  shot_right_scoop_lit_hit:
    grave_targets_completed: 1
  
  # Bonus score when completing the mode
  grave_targets_complete:
    score: 40000

show_player:
  # Show when each blinking target is hit
  shot_target_g_lit_hit:
    led_grave_target_show:
      speed: 2
      loops: 1
  shot_target_r_lit_hit:
    led_grave_target_show:
      speed: 2
      loops: 1
  shot_target_a_lit_hit:
    led_grave_target_show:
      speed: 2
      loops: 1
  right_ramp_hit:
    led_grave_target_show:
      speed: 2
      loops: 1
  shot_right_scoop_lit_hit:
    led_grave_target_show:
      speed: 2
      loops: 1

sound_player:
  shot_target_g_unlit_hit:
    blue_target:
      action: play
  shot_target_r_unlit_hit:
    blue_target:
      action: play
  shot_target_a_unlit_hit:
    blue_target:
      action: play
  right_ramp_hit:
    blue_target:
      action: play
