#config_version=6

##! mode: grave_targets
mode:
  start_events: ball_starting
  stop_events: ball_will_end
  priority: 200

# sequences:
#   grave_targets_sequence:
#     events:
#       - shot_target_g_lit_hit
#       - shot_target_r_lit_hit
#       - shot_target_a_lit_hit
#       - shot_right_ramp_lit_hit
#       - shot_right_scoop_lit_hit
#     restart_events: reset_targets
#     events_when_complete: grave_targets_sequence_complete

shot_groups:
  grave_targets_group:
    shots: shot_target_g, shot_target_r, shot_target_a

event_player:
  mode_grave_targets_started: reset_targets
  reset_targets: advance_target_g
  shot_right_scoop_lit_hit:
    - grave_targets_complete
  advance_scoop_to_solid:
    - debug_advance_scoop_to_solid

shot_profiles:
  target_profile:
    advance_on_hit: false
    states:
      - name: off
        show: off
      - name: lit
        show: show_blink
      - name: down
        show: "on"
  # target_profile_ramp:
  #   advance_on_hit: false
  #   states:
  #     - name: off
  #       show: off
  #     - name: lit
  #       show: show_blink
  #     - name: down
  #       show: "on"
  # scoop_profile:
  #   advance_on_hit: false
  #   states:
  #     - name: unlit
  #       show: off
  #     - name: lit
  #       show: show_blink
  #     - name: solid
  #       show: "on"

shots:
  shot_target_g:
    switches: s_target_g
    profile: target_profile
    advance_events: advance_target_g, shot_target_g_lit_hit
    reset_events: reset_targets
    show_tokens:
      led: led_letter_g
  shot_target_r:
    switches: s_target_r
    profile: target_profile
    advance_events: shot_target_g_lit_hit, shot_target_r_lit_hit
    reset_events: reset_targets
    show_tokens:
      led: led_letter_r
  shot_target_a:
    switches: s_target_a
    profile: target_profile
    advance_events: shot_target_r_lit_hit, shot_target_a_lit_hit
    reset_events: reset_targets
    show_tokens:
      led: led_letter_a
  shot_right_ramp:
    switches: s_ramp_top
    profile: target_profile
    advance_events: shot_target_a_lit_hit, shot_right_ramp_lit_hit
    reset_events: reset_targets
    show_tokens:
      led: led_ramp_1
  shot_right_scoop:
    switches: s_right_scoop
    profile: target_profile
    advance_events: shot_right_ramp_lit_hit, shot_right_scoop_lit_hit, advance_scoop_to_solid
    reset_events: reset_targets
    show_tokens:
      led: led_letter_e

# sequence_shots are defined in base mode

variable_player:
  shot_target_g_hit:
    score: 500
  shot_target_r_hit:
    score: 500
  shot_target_a_hit:
    score: 500
  shot_right_ramp_hit:
    score: 500
  shot_right_scoop_lit_hit:
    grave_targets_completed: 1
  # Bonus score when completing the mode
  grave_targets_complete:
    score: 2000

show_player:
  # Show when each blinking target is hit
  shot_target_g_lit_hit:
    led_targets:
      show: led_grave_target_show
      loops: 0
  shot_target_r_lit_hit:
    led_targets:
      show: led_grave_target_show
      loops: 0
  shot_target_a_lit_hit:
    led_targets:
      show: led_grave_target_show
      loops: 0
  shot_right_ramp_lit_hit:
    led_targets:
      show: led_grave_target_show
      loops: 0
  shot_right_scoop_lit_hit:
    led_targets:
      show: led_grave_target_show
      loops: 0
  
sound_player:
  shot_target_g_unlit_hit:
    sword_slice:
      action: play
  shot_target_r_unlit_hit:
    sword_slice:
      action: play
  shot_target_a_unlit_hit:
    sword_slice:
      action: play
  shot_right_ramp_lit_hit:
    sword_slice:
      action: play

