#config_version=6

config:
  - hardware.yaml
  - switches.yaml
  - coils.yaml
  - lights.yaml
  - devices.yaml
  - images.yaml
  - displays.yaml
  - slides.yaml

modes:
  - base
  - attract
  
playfields:
  playfield:
    tags: default
    default_source_device: bd_trough

