#config_version=6

slides:
  # welcome_slide:
  #   widgets:
  #     - type: text
  #       text: Addams Family
  #       font_size: 96
  #       color: purple
  #     - type: rectangle
  #       width: 740
  #       height: 120
  #       color: white
  attract_image_slide:
     widgets:
      - type: image
        image: af_bg
        x: center   
        y: middle  
  attract_video_slide:
     widgets:
      - type: video
        video: af_intro_video