#config_version=6

switches:
# flippers
  s_left_flipper:
    number: 0-0-19
    tags: left_flipper
  s_right_flipper:
    number: 0-0-17
    tags: right_flipper

# slingshots
  s_left_slingshot:
    number: 0-0-26
    tags: left_slingshot
  s_right_slingshot:
    number: 0-0-24
    tags: right_slingshot

# pop bumpers
  s_pop1:
    number: 0-0-1   
  s_pop2:
    number: 0-0-3 
  s_pop3:
    number: 0-0-8
  s_pop4:
    number: 0-0-2
  s_pop5:
    number: 0-0-9

# # scoops
#   s_scoop_center:
#     number:
#     tags: scoop
#   s_scoop_right:
#     number:
#     tags: scoop

# # outlanes
#   s_left_outlane:
#     number:
#   s_left_inlane1:
#     number:
#   s_left_inlane2:
#     number:
#   s_right_outlane:
#     number:
#   s_right_inlane:
#     number:


# trough
  s_trough1:
    number: 1-0-1
#   s_trough2:
#     number:
#   s_trough3:
#     number:
#   s_trough4:
#     number:
#   s_trough5:
#     number:

  

# miscellaneous
  s_startButton:
    number: 0-0-25
    tags: start
  s_right_inlane:
    number: 0-0-11
    tags: playfield_active
