#config_version=6

##! mode: mansion_modes
mode:
  start_events: ball_starting
  stop_events: ball_will_end
  priority: 1000

show_player:
  s_pop1_active:
    led_gy:
      show: led_gy_blink
      loops: 0