#config_version=6

##! mode: mansion_modes
mode:
  start_events: ball_starting
  stop_events: ball_will_end
  priority: 1000

event_player:
  # When pop bumpers mode completes
  pop_mode_complete:
    - mansion_mode_completion_celebration
    - mansion_pop_complete
  grave_targets_complete:
    - mansion_mode_completion_celebration
    - mansion_grave_complete

variable_player:
  pop_mode_complete:
    pop_bumpers_completed: 1
  grave_targets_complete:
    grave_targets_completed: 1

show_player:
  mansion_mode_completion_celebration:
    led_mansion_1:
      show: led_mansion_shine
      loops: 0


# sound_player:
#   mansion_mode_completion_celebration:
#     coin_complete:
#       action: play

