#config_version=6

##! mode: mansion_modes
mode:
  start_events: ball_starting
  stop_events: ball_will_end
  priority: 300

# Achievement group for mansion awards
achievement_groups:
  mansion_awards:
    achievements: grave_targets_award, pop_bumpers_award
    enable_events: mode_mansion_modes_started
    auto_select: true

# Individual mansion achievements
achievements:
  grave_targets_award:
    show_tokens:
      led: led_mansion_1
    show_when_selected: mansion_blink
    show_when_completed: "on"
    events_when_started: award_grave_targets
    complete_events: grave_targets_complete
    reset_events: ball_will_end
  pop_bumpers_award:
    show_tokens:
      led: led_mansion_2
    show_when_selected: mansion_blink
    show_when_completed: "on"
    events_when_started: award_pop_bumpers
    complete_events: pop_bumpers_complete
    reset_events: ball_will_end

# Center scoop shot for collecting selected achievement
shots:
  shot_center_scoop:
    switch: s_center_scoop
    profile: reward_scoop_profile
    advance_events: mode_mansion_modes_started
    reset_events: collect_available_rewards
    show_tokens:
      led: led_loop

shot_profiles:
  reward_scoop_profile:
    advance_on_hit: false
    states:
      - name: unlit
        show: off
      - name: lit
        show: mansion_blink

event_player:
  # When a mode completes, mark its achievement as complete
  grave_targets_complete:
    - debug_grave_targets_complete
  
  pop_bumpers_complete:
    - debug_pop_bumpers_complete
  
  # When center scoop is hit, collect the selected achievement
  shot_center_scoop_lit_hit:
    - collect_available_rewards
    - debug_center_scoop_hit
  
  # Award events for each achievement type
  award_grave_targets:
    - debug_grave_targets_awarded
  
  award_pop_bumpers:
    - debug_pop_bumpers_awarded

variable_player:
  # Collect available rewards - award points and reset
  collect_available_rewards:
    score: 50000
    grave_targets_reward_collected: 1
    pop_bumpers_reward_collected: 1

show_player:
  # Stop blinking and keep solid when reward is collected
  collect_available_rewards:
    led_mansion_1:
      show: "on"
      loops: 0
    led_mansion_2:
      show: "on"
      loops: 0

sound_player:
  # Sound when collecting rewards
  shot_center_scoop_lit_hit:
    grave_complete:
      action: play